### ISSUE TITLE
Pinksale ABI update

### ISSUE THREAD

**Issue by sjunaiduk** [tarik0/pinksale-abi#1]
Hi Tarik,

I recently came across your tremendous work with decompiling and reverse engineering solidity contracts, I appreciate the effort and it has helped me alot!

I was just wondering whether you plan to update the pinksale ABI? Also (I am a bit of a noob here sorry) I was trying to use this ABI for presale contracts on the pinksale test net but they didn't work not sure why.

And the reason I asked if you could update the ABI is because I'm trying to fetch the exact start time of when a pinksale presale goes public, because there is  both a whitelist timer and a public timer.

Thanks!

**Comment by tarik0** [comment]
I don't have a program schedule that uses Pinksale so I'm not gonna update it I need it again sorry.
